### ISSUE TITLE
Unable to link due to 'undefined reference to Aether::...'

### ISSUE THREAD

**Issue by tallbl0nde** [tallbl0nde/Aether#13]
@eXhumer I'm going to ping you here since attempting to compile both NX-Activity-Log and my other, top-secret project with Aether after your Makefile changes causes it to fail at the linking stage.
```
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: Slider.o: in function `CustomElm::Slider::setBarForegroundColour(SDL_Color)':
/mnt/d/Code/TriPlayer/Application/source/ui/element/Slider.cpp:141: undefined reference to `Aether::RoundProgressBar::setForegroundColour(SDL_Color)'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: Frame.o: in function `CustomElm::Frame::Frame(Main::Application*)':
/mnt/d/Code/TriPlayer/Application/source/ui/element/Frame.cpp:37: undefined reference to `Aether::List::List(int, int, int, int, Aether::Padding)'
collect2: error: ld returned 1 exit status
```

I've tried messing with a few things and I've got no idea what's wrong. The object files compile fine and the library builds fine. Are there any changes I need to make to their Makefiles?

Also on a side note, I've noticed `ThreadPool.o` sometimes recompiles even though I haven't changed the library source whatsoever.

**Comment by tallbl0nde** [comment]
I think I've found the issue: it's not compiling any files that are more than one subdirectory in (e.g. `/utils/SDLHelper` is compiled but `horizon/list/List` is not)

**Comment by eXhumer** [comment]
EEEEEEEEE. Forgot there was more. TY for noticing.
